import { fetchWithTimeout } from '../../lib/utils';

/**
 * =============================================================================
 * THREAT FEED — Signed remote refresh for the phishing/malware blocklist
 * =============================================================================
 *
 * The bundled snapshot (assets/phishlist.json) is trusted because it ships
 * inside the Chrome-signed extension package. To keep that snapshot current
 * without shipping a new extension build, this service fetches a remote,
 * Ed25519-signed update and only accepts it when ALL of the following hold:
 *
 *   1. The signature verifies against the embedded public key (authenticity).
 *   2. The feed's `updated` timestamp is within MAX_FEED_AGE_MS (freshness).
 *   3. The feed is newer than the last accepted one (anti-rollback).
 *
 * On any failure the bundled snapshot remains in effect. The private key is
 * held only by the developer (as a GitHub Actions secret) — it never ships in
 * the extension.
 * =============================================================================
 */

// Ed25519 public key (hex) corresponding to the developer's signing key.
// Generated by scripts/generate-threat-keys.js.
const THREAT_FEED_PUBLIC_KEY_HEX =
    'eb6d4deff2c95446605cf24c8cc811b4948f3e01db0196177a72359f03c35856';

// Committed signed artifact, served raw from the main branch. The signature
// makes the transport untrusted-safe; a CDN or proxy cannot forge an update.
const THREAT_FEED_URL =
    'https://raw.githubusercontent.com/luca-liceti/TraceGuard-Privacy-Extension/main/traceguard-extension/src/assets/phishlist.signed.json';

// Reject feeds older than this even if signed (defends against replays of a
// valid-but-stale feed).
const MAX_FEED_AGE_MS = 14 * 24 * 60 * 60 * 1000; // 14 days

const LAST_ACCEPTED_KEY = 'threatFeedLastUpdated';

interface SignedPhishlist {
    version: string;
    updated: string;
    domains: string[];
    signature: string;
}

function hexToBytes(hex: string): Uint8Array<ArrayBuffer> {
    const clean = hex.replace(/\s+/g, '');
    if (clean.length % 2 !== 0 || clean.length === 0) throw new Error('Invalid public key hex');
    const bytes = new Uint8Array(clean.length / 2);
    for (let i = 0; i < bytes.length; i++) {
        bytes[i] = parseInt(clean.substr(i * 2, 2), 16);
    }
    return bytes;
}

function base64ToBytes(b64: string): Uint8Array<ArrayBuffer> {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
}

/** The exact byte string the signer signed. Field order is load-bearing. */
function canonicalPayload(version: string, updated: string, domains: string[]): string {
    return JSON.stringify({ version, updated, domains });
}

async function verifySignature(canonical: string, signatureB64: string, publicKeyHex: string): Promise<boolean> {
    try {
        const key = await crypto.subtle.importKey(
            'raw',
            hexToBytes(publicKeyHex),
            { name: 'Ed25519' },
            false,
            ['verify']
        );
        const signature = base64ToBytes(signatureB64);
        const data = new TextEncoder().encode(canonical);
        return await crypto.subtle.verify({ name: 'Ed25519' }, key, signature, data);
    } catch (err) {
        console.warn('[threat-feed] Signature verification error:', err);
        return false;
    }
}

/**
 * Verify an Ed25519 signature over the canonical `{ version, updated, domains }`
 * payload using an arbitrary public key. Exported for unit testing.
 */
export async function verifySignedFeed(data: SignedPhishlist, publicKeyHex: string): Promise<boolean> {
    const canonical = canonicalPayload(data.version, data.updated, data.domains);
    return verifySignature(canonical, data.signature, publicKeyHex);
}

/**
 * Fetch, verify, and return an updated set of malicious domains, or null if
 * the remote feed is missing, stale, malformed, or fails verification.
 */
export async function refreshThreatFeed(): Promise<string[] | null> {
    try {
        const res = await fetchWithTimeout(THREAT_FEED_URL, { cache: 'no-store' });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);

        const data = (await res.json()) as SignedPhishlist;
        if (
            !data ||
            typeof data.version !== 'string' ||
            typeof data.updated !== 'string' ||
            !Array.isArray(data.domains) ||
            typeof data.signature !== 'string'
        ) {
            throw new Error('Malformed signed feed');
        }

        const updatedTs = Date.parse(data.updated);
        if (!Number.isFinite(updatedTs)) throw new Error('Invalid updated timestamp');
        if (Date.now() - updatedTs > MAX_FEED_AGE_MS) throw new Error('Feed is too old');

        // Anti-rollback: refuse anything not strictly newer than what we accepted.
        const stored = await chrome.storage.local.get<{ threatFeedLastUpdated?: string }>(LAST_ACCEPTED_KEY);
        const lastUpdated = typeof stored.threatFeedLastUpdated === 'string'
            ? Date.parse(stored.threatFeedLastUpdated)
            : 0;
        if (updatedTs <= lastUpdated) throw new Error('Feed is not newer than the current one');

        if (!(await verifySignedFeed(data, THREAT_FEED_PUBLIC_KEY_HEX))) throw new Error('Invalid signature');

        await chrome.storage.local.set({ [LAST_ACCEPTED_KEY]: data.updated });
        console.log(`[threat-feed] Accepted signed feed v${data.version} with ${data.domains.length} domains`);
        return data.domains;
    } catch (err) {
        console.warn('[threat-feed] Refresh failed; keeping bundled snapshot:', err);
        return null;
    }
}
