/**
 * =============================================================================
 * VITE CONFIGURATION - Build Tool Setup for TraceGuard
 * =============================================================================
 * 
 * WHAT THIS FILE DOES:
 * Vite is our build tool - it bundles all our TypeScript, React, and CSS files
 * into a format that the browser can run. This config tells Vite how to do that.
 * 
 * KEY SETTINGS:
 * - Uses React plugin for JSX/TSX support
 * - Uses crx plugin to build as a Chrome extension (from manifest.json)
 * - Copies static assets (like phishlist.json and the privacy databases) to the output folder
 * - Sets up path aliases (@ = src folder) for cleaner imports
 * 
 * BUILD OUTPUTS:
 * - Dashboard: The full privacy dashboard UI
 * - Popup: The small popup when you click the extension icon
 * - Background: The service worker that runs in the background
 * - Content scripts: Code injected into web pages
 * 
 * TO BUILD: Run `npm run build` - output goes to the /dist folder
 * TO DEV: Run `npm run dev` - starts a dev server with hot reload
 * =============================================================================
 */
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { crx } from '@crxjs/vite-plugin'
import { viteStaticCopy } from 'vite-plugin-static-copy'
import path from 'path'
import fs from 'fs'
import rawManifest from './manifest.json'
import pkg from './package.json'

const DEV_SERVER_PORT = 5173

// CRXJS serves the extension from the Vite dev server while developing, and the
// background worker proxies the popup's own request there. The manifest pins
// connect-src to the extension and the two feed origins, so that proxy fetch is
// blocked and the popup opens on ERR_FAILED. Allow the dev server and its HMR
// socket only for `vite dev`; the packaged manifest keeps the tight policy.
function allowDevServer(policy: string | undefined): string | undefined {
  if (!policy) return policy
  const origin = `http://localhost:${DEV_SERVER_PORT}`
  const socket = `ws://localhost:${DEV_SERVER_PORT}`
  return policy.replace(
    /connect-src([^;]*)/,
    (_match, sources: string) => `connect-src${sources} ${origin} ${socket}`,
  )
}

// ToS;DR ships as a small index plus detail shards, generated by
// `npm run build:tosdr` and committed. The copy targets are only added when the
// files exist, so a build never fails on a checkout that has not generated them
// yet.
const tosdrDetailsDir = path.resolve(__dirname, 'src/assets/tosdr/details')
const hasTosdrDetails = fs.existsSync(tosdrDetailsDir) &&
  fs.readdirSync(tosdrDetailsDir).some((f) => f.endsWith('.json'))
const tosdrTargets = [
  fs.existsSync(path.resolve(__dirname, 'src/assets/tosdr-index.json'))
    ? { src: 'src/assets/tosdr-index.json', dest: 'assets' }
    : null,
  hasTosdrDetails
    ? { src: 'src/assets/tosdr/details/*.json', dest: 'assets/tosdr/details' }
    : null,
].filter(Boolean) as { src: string; dest: string }[]

export default defineConfig(({ command }) => {
  const isDev = command === 'serve'

  // package.json is the single source of truth for the version. Inject it into
  // the manifest at build time so the packaged extension always matches.
  const manifest = {
    ...rawManifest,
    version: pkg.version,
    ...(isDev
      ? {
          content_security_policy: {
            ...rawManifest.content_security_policy,
            extension_pages: allowDevServer(rawManifest.content_security_policy?.extension_pages),
          },
        }
      : {}),
  }

  return {
    base: './',
    plugins: [
      react(),
      crx({ manifest }),
      viteStaticCopy({
        targets: [
          {
            src: 'src/assets/phishlist.json',
            dest: 'assets'
          },
          {
            src: 'src/assets/tracker-radar.json',
            dest: 'assets'
          },
          {
            src: 'src/assets/cookie-database.json',
            dest: 'assets'
          },
          {
            src: 'src/assets/easyprivacy-domains.json',
            dest: 'assets'
          },
          {
            src: 'src/assets/disconnect-services.json',
            dest: 'assets'
          },
          ...tosdrTargets
        ]
      })
    ],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
    build: {
      chunkSizeWarningLimit: 500,
      rollupOptions: {
        input: {
          dashboard: 'src/dashboard/index.html',
          popup: 'src/popup/index.html',
        },
        output: {
          entryFileNames: 'assets/[name]-[hash].js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash].[ext]',
        },
      },
    },
    esbuild: {
      drop: ['debugger'],
      pure: ['console.log', 'console.info', 'console.debug', 'console.trace'],
    },
    server: {
      port: DEV_SERVER_PORT,
      strictPort: true,
      hmr: {
        port: DEV_SERVER_PORT,
      },
    },
  }
})
